# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the  Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 100
  reviewers:
  - planetf1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
  reviewers:
  - planetf1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
  reviewers:
    - planetf1
